# Generated by Django 4.1.2 on 2023-02-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rotulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_Interno', models.CharField(max_length=200, verbose_name='Codigo Interno')),
                ('n_Cajas', models.CharField(max_length=200, verbose_name='Numero de Cajas')),
                ('Zona_remitente', models.CharField(max_length=200, verbose_name='Zona que Despacha')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'rotulos',
                'verbose_name_plural': 'rotulos',
                'ordering': ['-created'],
            },
        ),
    ]
